# Generated by Django 2.2.2 on 2019-06-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='text',
            field=models.TextField(max_length=2000),
        ),
    ]
