# Generated by Django 2.2.2 on 2019-06-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_auto_20190621_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='menucategories',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
